# Generated by Django 4.2.1 on 2023-06-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crawling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("press", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=30)),
                ("article", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Godsummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("press", models.CharField(max_length=10, null=True)),
                ("title", models.TextField()),
                ("category", models.CharField(max_length=10, null=True)),
                ("article", models.TextField()),
                ("datetime", models.DateTimeField()),
                ("link", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
    ]
