# Generated by Django 4.2.1 on 2023-06-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summaryapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawling",
            name="press",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="crawling",
            name="title",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
